#pragma once
#include <cuda_runtime.h>
#include "Image.h"
#include "GPUCamera.cuh"
#include "CommonCUDA.cuh"
#include "GPUVecOps.h"
#include "GPUHit.h"
#include "GPURay.h"
#include "GPULight.h"
#include "GPUMaterial.h"